#!/bin/bash

source "$(dirname "$0")/ft_util_inc_var"

$S_LOG -s debug -d $S_NAME "Cleaning start ${1}"

if [ -z "${1}" ] ; then exit ; fi  

find ${1}* -maxdepth 0 -type f -mtime +7 -name '*.bak' -delete -print | $S_LOG -d $S_NAME -d -i
returncode=$? # store the exit code of the command
# ls -al ${1}*

$S_LOG -d $S_NAME -d ${1} "cleaning bak exited with code $returncode"
